export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";
export const FETCH_DATA_START = "FETCH_DATA_START";
export const SET_FILTER_DATA = "SET_FILTER_DATA";
